[package]
name = "nextalign"
description = "Nucleotide sequence alignment and translation"
version = "2.0.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
bio = "0.39.0"
jemallocator-global = "0.3.2"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
