[changelog]

header = """
<details>
  <summary><h3>Commit history</h3> (click to expand)</summary>
"""

# This uses "Tera" template language.
# Docs: https://tera.netlify.app/docs/#introduction
body = """
{% for commit in commits %}
 - [[`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/{{ get_env(name="GITHUB_REPOSITORY") }}/commit/{{ commit.id }})] {{ commit.message }}
{% endfor %}
"""

trim = true

footer = """</details>"""


[git]

# parse the commits based on https://www.conventionalcommits.org
conventional_commits = false

# filter out the commits that are not conventional
filter_unconventional = false

# regex for preprocessing the commit messages
commit_preprocessors = []

# regex for parsing and grouping commits
commit_parsers = []

# filter out the commits that are not matched by commit parsers
filter_commits = false

# glob pattern for matching git tags
tag_pattern = "[0-9]*"

# regex for skipping tags
skip_tags = ""

# regex for ignoring tags
ignore_tags = ""

# sort the tags chronologically
date_order = true

# sort the commits inside sections by oldest/newest order
sort_commits = "oldest"
