version: '3.7'

services:
  nextalign_builder_dev:
    container_name: nextalign_builder_dev
    image: neherlab/nextalign_builder:latest
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - USER=user
        - GROUP=user
        - UID=$UID
        - GID=$GID
    command: ['make', 'dev']
    volumes:
      - ./:/src
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - COLORTERM=truecolor
      - TERM=xterm-256color
    restart: 'no'
    init: true
    user: '${UID}'
    tty: true
