[toolchain]
channel = "1.60.0"
profile = "default"
targets = [
  "aarch64-apple-darwin",
  "aarch64-unknown-linux-gnu",
  "wasm32-unknown-unknown",
  "x86_64-apple-darwin",
  "x86_64-pc-windows-gnu",
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
]
components = [
  "cargo",
  "clippy",
  "rust-analysis",
  "rust-docs",
  "rust-src",
  "rust-std",
  "rustc",
  "rustfmt",
]
