[package]
name = "nextclade-web"
description = "Alignment, mutation calling, phylogenetic placement, clade assignment and quality control checks for viral genetic sequences. WebAssembly module."
version = "2.0.0"
edition = "2021"
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
log = "0.4.16"
nextclade = { path = "../nextclade", default-features = false, features = ["wasm"] }
serde = { version = "1.0.136", features = ["derive"] }
wasm-bindgen = { version = "0.2.79", features = ["serde-serialize"] }
wasm-logger = "0.2.0"
web-sys = { version = "0.3.56", features = ["console"] }
wee_alloc = "0.4.5"

[dev-dependencies]
wasm-bindgen-test = "0.3.29"
