[package]
name = "nextclade"
description = "Alignment, mutation calling, phylogenetic placement, clade assignment and quality control checks for viral genetic sequences. Library."
version = "2.0.0"
documentation = "https://docs.nextstrain.org/projects/nextclade/en/stable/"
homepage = "https://clades.nextstrain.org/"
edition = "2021"
license = "MIT"
publish = false


[lib]
crate-type = ["lib"]

[dependencies]
assert2 = "0.3.6"
auto_ops = "0.3.0"
bio = "0.40.0"
bio-types = "0.12.1"
chrono = { version = "0.4.19", default-features = false, features = ["clock", "std"] }
clap = { version = "3.1.6", features = ["derive"] }
clap-verbosity-flag = "1.0.0"
clap_complete = "3.1.1"
clap_complete_fig = "3.1.0"
color-eyre = "0.6.0"
csv = "1.1.6"
ctor = "0.1.21"
env_logger = "0.9.0"
eyre = "0.6.5"
getrandom = { version = "0.2.4" }
indexmap = { verson = "1.8.0", features = ["serde"] }
itertools = "0.10.3"
lazy_static = "1.4.0"
log = "0.4.14"
map_in_place = "0.1.0"
mimalloc = { version = "0.1.27", default-features = false, optional = true }
owo-colors = "3.2.0"
phf = { version = "0.10.1", features = ["macros"] }
pretty_assertions = "1.0.0"
rstest = { version = "0.12.0", optional = true }
rstest_reuse = { version = "0.1.3", optional = true }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0.79", features = ["preserve_order", "indexmap", "unbounded_depth"] }
traversal = "0.1.2"
typescript-definitions = { path = "../../3rdparty/typescript-definitions", features = [], optional = true }
typescript-definitions-derive = { path = "../../3rdparty/typescript-definitions/typescript-definitions-derive", features = [], optional = true }
validator = { version = "0.12", features = ["derive"] }
wasm-bindgen = { version = "0.2.79", features = ["serde-serialize"], optional = true }

[dev-dependencies]
mimalloc = { version = "0.1.27", default-features = false }
rstest = { version = "0.12.0" }
rstest_reuse = { version = "0.1.3" }
typescript-definitions = { path = "../../3rdparty/typescript-definitions", features = [] }
typescript-definitions-derive = { path = "../../3rdparty/typescript-definitions/typescript-definitions-derive", features = [] }
wasm-bindgen = { version = "0.2.79", features = ["serde-serialize"] }

[features]
default = ["non-wasm"]
wasm = [
  "getrandom/js",
  "typescript-definitions",
  "typescript-definitions-derive",
  "wasm-bindgen",
]
non-wasm = [
  "mimalloc",
  "rstest",
  "rstest_reuse"
]


[profile.test]
debug = true

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
