[package]
name = "nextclade"
description = "Alignment, mutation calling, phylogenetic placement, clade assignment and quality control checks for viral genetic sequences"
version = "2.0.0"
documentation = "https://docs.nextstrain.org/projects/nextclade/en/stable/"
homepage = "https://clades.nextstrain.org/"
edition = "2021"
license = "MIT"
publish = false


[lib]
crate-type = ["lib"]

[dependencies]
assert2 = "0.3.6"
auto_ops = "0.3.0"
bio = "0.41.0"
bio-types = "0.12.1"
chrono = { version = "0.4.19", default-features = false, features = ["clock", "std"] }
clap = { version = "3.1.8", features = ["derive"] }
clap-verbosity-flag = "1.0.0"
clap_complete = "3.1.1"
clap_complete_fig = "3.1.4"
color-eyre = "0.6.1"
crossbeam = "0.8.1"
crossbeam-channel = "0.5.4"
csv = "1.1.6"
ctor = "0.1.22"
env_logger = "0.9.0"
eyre = "0.6.8"
getrandom = "0.2.6"
indexmap = { verson = "1.8.0", features = ["serde"], version = "1.8.1" }
itertools = "0.10.3"
lazy_static = "1.4.0"
log = "0.4.16"
map_in_place = "0.1.0"
num = "0.4.0"
num-traits = "0.2.14"
num_cpus = "1.13.1"
owo-colors = "3.3.0"
phf = { version = "0.10.1", features = ["macros"] }
pretty_assertions = "1.2.1"
regex = "1.5.5"
rstest = { version = "0.12.0", optional = true }
rstest_reuse = { version = "0.3.0", optional = true }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0.79", features = ["preserve_order", "indexmap", "unbounded_depth"] }
traversal = "0.1.2"
typescript-definitions = { path = "../../3rdparty/typescript-definitions", features = [], optional = true }
typescript-definitions-derive = { path = "../../3rdparty/typescript-definitions/typescript-definitions-derive", features = [], optional = true }
validator = { version = "0.14.0", features = ["derive"] }
wasm-bindgen = { version = "0.2.79", features = ["serde-serialize"], optional = true }

[target.'cfg(all(target_family = "linux", target_arch = "x86_64"))'.dependencies]
mimalloc = { version = "0.1.28", default-features = false, optional = true }

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }
rstest = "0.12.0"
rstest_reuse = "0.3.0"
typescript-definitions = { path = "../../3rdparty/typescript-definitions", features = [] }
typescript-definitions-derive = { path = "../../3rdparty/typescript-definitions/typescript-definitions-derive", features = [] }
wasm-bindgen = { version = "0.2.79", features = ["serde-serialize"] }

[features]
default = ["non-wasm"]
wasm = [
  "getrandom/js",
  "typescript-definitions",
  "typescript-definitions-derive",
  "wasm-bindgen",
]
non-wasm = [
  "rstest",
  "rstest_reuse"
]


[[bench]]
name = "bench_create_stripes"
harness = false

[[bench]]
name = "bench_seed_match"
harness = false

