[toolchain]
channel = "1.58.1"
profile = "default"
targets = ["wasm32-unknown-unknown", "x86_64-unknown-linux-gnu"]
components = [
  "cargo",
  "clippy",
  "rust-analysis",
  "rust-docs",
  "rust-src",
  "rust-std",
  "rustc",
  "rustfmt",
]
