version: 2.1

orbs:
  win: circleci/windows@2.4.0


# Reference. Allows to restrict a job to release branch
release_only: &release_only
  filters:
    branches:
      only: nextalign-release


jobs:
  Build-Linux-x86_64:
    resource_class: medium

    machine:
      image: ubuntu-2004:202010-01

    steps:
      - checkout

      - run:
          name: 'Check release version'
          command: |
            make check-release-version

      - restore_cache:
          name: 'Restore docker image cache'
          keys:
            - cache-nextalign-v1-docker_images

      - run:
          name: 'Load docker image cache'
          command: |
            make docker-cache-load

      - run:
          name: 'Build "Builder" container image'
          command: |
            make docker-prod-build

      - run:
          name: 'Store docker image cache'
          command: |
            make docker-cache-save

      - save_cache:
          name: 'Save docker image cache'
          key: cache-nextalign-v1-docker_images-{{ arch }}-{{ checksum "Dockerfile" }}
          paths:
            - docker_images

      - restore_cache:
          name: 'Restore build cache'
          keys:
            - cache-nextalign-v1-cache-{{ arch }}-{{ checksum "conanfile.txt" }}

      - run:
          name: 'Run "Builder" container'
          command: |
            make docker-prod-run

      - save_cache:
          name: 'Save build cache'
          key: cache-nextalign-v1-docker_images-{{ arch }}-{{ checksum "Dockerfile" }}
          paths:
            - .cache

      - store_artifacts:
          name: 'Store Linux x86_64 binary'
          path: .out/bin/nextalign-Linux-x86_64
          destination: nextalign-Linux-x86_64

      - run:
          name: Save artifact info
          command: |
            artifacts=$(curl -X GET "https://circleci.com/api/v2/project/github/neherlab/nextclade/$CIRCLE_BUILD_NUM/artifacts" \
            -H "Accept: application/json" \
            -u "$CIRCLE_API_TOKEN:")
            echo "export ARTIFACT_LINUX_x86_64=$artifacts" >> $BASH_ENV

  Build-MacOS:
    parameters:
      macos_arch:
        type: string

    macos:
      xcode: "12.4.0"

    steps:
      - checkout

      - restore_cache:
          name: 'Restore homebrew cache'
          keys:
            - cache-nextalign-v1-homebrew-{{ arch }}

      - run:
          name: 'Install build tools'
          command: |
            set -x
            brew install -q cmake conan coreutils cppcheck
            conan profile new default --detect
            conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
          environment:
            HOMEBREW_NO_AUTO_UPDATE: 1
            CONAN_USER_HOME: '/Users/distiller/project/.cache/conan'

      - save_cache:
          name: 'Save homebrew cache'
          key: cache-nextalign-v1-homebrew-{{ arch }}
          paths:
            - '~/Library/Caches/Homebrew'
            - '/usr/local/Homebrew'

      - restore_cache:
          name: 'Restore build cache'
          keys:
            - cache-nextalign-v3-cache-{{ arch }}-{{ checksum "conanfile.txt" }}-<< parameters.macos_arch >>

      - run:
          name: Run macOS << parameters.macos_arch >> build
          command: |
            make prod
          environment:
            CONAN_USER_HOME: '/Users/distiller/project/.cache/conan'
            MACOS_ARCH: << parameters.macos_arch >>

      - save_cache:
          name: 'Save build cache'
          key: cache-nextalign-v3-cache-{{ arch }}-{{ checksum "conanfile.txt" }}-<< parameters.macos_arch >>
          paths:
            - .cache

      - store_artifacts:
          name: Persist artifacts in CircleCI Artifacts (macOS << parameters.macos_arch >>)
          path: .out/bin/nextalign-MacOS-<< parameters.macos_arch >>
          destination: nextalign-MacOS-<< parameters.macos_arch >>

      - run:
          name: Save artifact info
          command: |
            artifacts=$(curl -X GET "https://circleci.com/api/v2/project/github/neherlab/nextclade/$CIRCLE_BUILD_NUM/artifacts" \
            -H "Accept: application/json" \
            -u "$CIRCLE_API_TOKEN:")
            echo "export ARTIFACT_MACOS_<< parameters.macos_arch >>=$artifacts" >> $BASH_ENV

  Build-Windows-x86_64:
    executor:
      name: win/default
      size: medium
      shell: powershell.exe

    steps:
      - checkout

      - run:
          name: Install build tools
          command: |
            choco install cmake conan -y

      - run:
          command: |
            .\scripts\build_locally.ps1

  Release:
    resource_class: medium

    machine:
      image: ubuntu-2004:202010-01

    steps:
      - checkout

      - run:
          name: "Print Artifact info"

          command: |
            set -x
            echo "ARTIFACT_MACOS_x86_64"
            echo "-------------------------------------------------------"
            echo "$ARTIFACT_MACOS_x86_64"
            echo "-------------------------------------------------------"
            echo "ARTIFACT_LINUX_x86_64"
            echo "-------------------------------------------------------"
            echo "$ARTIFACT_LINUX_x86_64"
            echo "-------------------------------------------------------"

      #- run:
      #    name: "Publish Release on GitHub"
      #    command: |
      #      GHR_VERSION=0.13.0
      #      pushd ${HOME} >/dev/null && curl -fsSL "https://github.com/tcnksm/ghr/releases/download/v${GHR_VERSION}/ghr_v${GHR_VERSION}_linux_amd64.tar.gz" | tar -xz --directory="$(pwd)" --strip-components=1 "ghr_v${GHR_VERSION}_linux_amd64/ghr"; popd >/dev/null
      #      VERSION=$(.out/bin/nextalign-Linux-x86_64 --version)
      #      ${HOME}/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete nextalign-${VERSION} .out/bin
      #
      #- run:
      #    name: "Publish Docker Image to Docker Hub"
      #    command: |
      #      echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      #      scripts/publish_docker_images.sh


workflows:
  version: 2
  build:
    jobs:
#      - Build-Linux-x86_64:
#         filters:
#           branches:
#             only: macos
#         # <<: *release_only
#
#      - Build-MacOS:
#          matrix:
#            parameters:
#              macos_arch:
#               - x86_64
#               # - arm64 # Currently broken, because of Intel TBB
#          filters:
#            branches:
#              only: macos

#      - Release:
#          requires:
#            - Build-Linux-x86_64
#            - Build-MacOS
       - Build-Windows-x86_64:
          filters:
            branches:
              only: windows
