[future-incompat-report]
frequency = 'always'

[profile.dev]
codegen-units = 32
incremental = true
lto = "off"

[profile.release]
codegen-units = 1
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
strip = true

[profile.bench]
codegen-units = 1
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
strip = true

[profile.test]
debug = true

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-ld"
ar = "aarch64-linux-gnu-ar"

[target.x86_64-apple-darwin]
# linker = "x86_64-apple-darwin20.2-clang"
# ar = "x86_64-apple-darwin20.2-ar"

[target.aarch64-apple-darwin]
linker = "aarch64-apple-darwin20.2-clang"
ar = "aarch64-apple-darwin20.2-ar"
