[package]
name = "nextclade-cli"
description = "Alignment, mutation calling, phylogenetic placement, clade assignment and quality control checks for viral genetic sequences. Command-line tools."
version = "2.0.0"
edition = "2021"
license = "MIT"
publish = false


[dependencies]
assert2 = "0.3.6"
bio = "0.40.0"
chrono = { version = "0.4.19", default-features = false, features = ["clock", "std"] }
clap = { version = "3.1.6", features = ["derive"] }
color-eyre = "0.6.1"
ctor = "0.1.22"
env_logger = "0.9.0"
eyre = "0.6.7"
itertools = "0.10.3"
log = "0.4.14"
nextclade = { path = "../nextclade" }
owo-colors = "3.3.0"
pretty_assertions = "1.2.0"
rstest = "0.12.0"
rstest_reuse = "0.3.0"

[target.'cfg(all(target_family = "linux", target_arch = "x86_64"))'.dependencies]
mimalloc = { version = "0.1.28", default-features = false, optional = true }

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
