[package]
name = "nextclade-cli"
description = "Alignment, mutation calling, phylogenetic placement, clade assignment and quality control checks for viral genetic sequences. Command-line tools."
version = "2.0.0"
edition = "2021"
license = "MIT"
publish = false


[dependencies]
assert2 = "0.3.6"
bio = "0.39.1"
chrono = { version = "0.4.19", default-features = false, features = ["clock", "std"] }
clap = { version = "3.0.10", features = ["derive"] }
color-eyre = "0.6.0"
ctor = "0.1.21"
env_logger = "0.9.0"
eyre = "0.6.5"
itertools = "0.10.3"
log = "0.4.14"
mimalloc = { version = "0.1.27", default-features = false }
nextclade = { path = "../nextclade" }
owo-colors = "3.2.0"
pretty_assertions = "1.0.0"
rstest = "0.12.0"
rstest_reuse = "0.1.3"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
